# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'Installing vagrant-disksize Plugin...'
  system('vagrant plugin install vagrant-disksize')
end

unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntudev" , primary: true do |ubuntudev|
 
  ubuntudev.vm.box = "ubuntu/jammy64"
  #ubuntudev.vm.box_version = "20211026.0.0"
  ubuntudev.vm.hostname = "ubuntunifidev"
  ubuntudev.disksize.size = '75GB'
  ubuntudev.vbguest.auto_update = true
  ubuntudev.vm.provider :virtualbox do |vb|
	  vb.customize ["modifyvm"     , :id, "--memory", "16384"]
      vb.customize ["modifyvm"     , :id, "--name"  , "Ubuntu NiFi Dev"]
	  #Use VBox 6.1.30 for this. 6.1.32 and 6.1.34 have issues with multiple CPUs
      vb.customize ["modifyvm"     , :id, "--cpus"  , 2]
	  vb.customize ["modifyvm"     , :id, "--clipboard","bidirectional"]
	  vb.customize ["modifyvm"     , :id, "--vram","64"]
  end

  #this starts provisioning the machine
  ubuntudev.vm.provision :shell, path: "provision.sh"
  end

end