version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      #Should be the same as the service. Zookeeper will indicate this as bootstrap server
      #in order to access Kafka from the Docker host, make sure kafka resolves to localhost, override the bootstrap server or start tooling from containers inside the same network
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nifi:
    image: apache/nifi:1.15.1
    ports:
      - "8443:8443"
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin
      SINGLE_USER_CREDENTIALS_PASSWORD: Welcome010101
      #docker exec -it comp_nifi_1 /bin/bash
  nifi-registry:
    image: apache/nifi-registry:1.15.1
    ports:
      - "18080:18080"
