# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'Installing vagrant-disksize Plugin...'
  system('vagrant plugin install vagrant-disksize')
end

#requires https://www.vagrantup.com/docs/providers/vmware/vagrant-vmware-utility
unless Vagrant.has_plugin?("vagrant-vmware-desktop")
  puts 'Installing vagrant-vmware-desktop Plugin...'
  system('vagrant plugin install vagrant-vmware-desktop')
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "ubuntudev" , primary: true do |ubuntudev|
  config.vm.provider "vmware_desktop"
  config.vm.network "public_network"  
  config.vm.synced_folder ".", "/vagrant", disabled: false
  ubuntudev.vm.box = "generic/ubuntu2104"
  ubuntudev.vm.box_version = "3.6.8"
  ubuntudev.vm.hostname = "ubuntunifidev"
  ubuntudev.disksize.size = '75GB'
  ubuntudev.vm.provider :vmware_desktop do |v|
	v.vmx["memsize"] = "8192"
	v.vmx["numvcpus"] = "6"
	v.vmx["vmci0.present"]  = "FALSE"
	v.gui = true
  end

  #this starts provisioning the machine
  ubuntudev.vm.provision :shell, path: "provision.sh"
  end

end


